#!/bin/sh
set -e

DIST="/etc/nginx/conf.d/default.conf.dist"
ORIG="/etc/nginx/conf.d/default.conf"
if [ ! -e $DIST ]; then
  cp -f $ORIG $DIST
else
  cp -f $DIST $ORIG
fi
rm -f /etc/nginx/conf.d/realip.conf

NGINX_SERVER_NAME=${NGINX_SERVER_NAME:-}
if [ -n "${NGINX_SERVER_NAME}" ]; then
    sed -i -e "s|^    server_name  localhost;|    server_name  ${NGINX_SERVER_NAME};|" /etc/nginx/conf.d/default.conf
fi

NGINX_ROOT=${NGINX_ROOT:-}
if [ -n "${NGINX_ROOT}" ]; then
    sed -i -e "s|^    root   /usr/share/nginx/html;|    root   ${NGINX_ROOT};|" /etc/nginx/conf.d/default.conf
fi

NGINX_REAL_IP_HEADER=${NGINX_REAL_IP_HEADER:-}
if [ -n "${NGINX_REAL_IP_HEADER}" ]; then
    echo "real_ip_header ${NGINX_REAL_IP_HEADER};" >> /etc/nginx/conf.d/realip.conf
fi

NGINX_SET_REAL_IP_FROM=${NGINX_SET_REAL_IP_FROM:-}
if [ -n "${NGINX_SET_REAL_IP_FROM}" ]; then
    echo "set_real_ip_from ${NGINX_SET_REAL_IP_FROM};" >> /etc/nginx/conf.d/realip.conf
fi


FASTCGI_PASS=${FASTCGI_PASS:-}
if [ -n "${FASTCGI_PASS}" ]; then
    sed -i -e "s| fastcgi_pass 127\.0\.0\.1:9000;| fastcgi_pass ${FASTCGI_PASS};|" /etc/nginx/conf.d/default.conf
fi

FASTCGI_READ_TIMEOUT=${FASTCGI_READ_TIMEOUT:-}
if [ -n "${FASTCGI_READ_TIMEOUT}" ]; then
    sed -i -e "s| fastcgi_read_timeout 60;| fastcgi_read_timeout ${FASTCGI_READ_TIMEOUT};|" /etc/nginx/conf.d/default.conf
fi

FASTCGI_SEND_TIMEOUT=${FASTCGI_SEND_TIMEOUT:-}
if [ -n "${FASTCGI_SEND_TIMEOUT}" ]; then
    sed -i -e "s| fastcgi_send_timeout 60;| fastcgi_send_timeout ${FASTCGI_SEND_TIMEOUT};|" /etc/nginx/conf.d/default.conf
fi

FASTCGI_BUFFERS=${FASTCGI_BUFFERS:-}
if [ -n "${FASTCGI_BUFFERS}" ]; then
    sed -i -e "s| fastcgi_buffers 8 8k;| fastcgi_buffers ${FASTCGI_BUFFERS};|" /etc/nginx/conf.d/default.conf
fi

FASTCGI_BUFFER_SIZE=${FASTCGI_BUFFER_SIZE:-}
if [ -n "${FASTCGI_BUFFER_SIZE}" ]; then
    sed -i -e "s| fastcgi_buffer_size 8k;| fastcgi_buffer_size ${FASTCGI_BUFFER_SIZE};|" /etc/nginx/conf.d/default.conf
fi

exec "$@"
