#!/bin/sh
set -e

BASE="/var/www/app"

DIST="/usr/local/etc/php-fpm.d/www.conf.dist"
ORIG="/usr/local/etc/php-fpm.d/www.conf"
if [ ! -e $DIST ]; then
  cp -f $ORIG $DIST
else
  cp -f $DIST $ORIG
fi
rm -f /usr/local/etc/php/conf.d/docker.ini

# php config
if [ -n "${TZ}" ]; then
    echo "date.timezone = ${TZ}" >> /usr/local/etc/php/conf.d/docker.ini
fi

if [ -n "${PHP_MEMORY_LIMIT}" ]; then
    echo "memory_limit = ${PHP_MEMORY_LIMIT}" >> /usr/local/etc/php/conf.d/docker.ini
fi

PHP_DISPLAY_ERRORS=${PHP_DISPLAY_ERRORS:-Off}
if [ -n "${PHP_DISPLAY_ERRORS}" ]; then
    echo "display_errors = ${PHP_DISPLAY_ERRORS}" >> /usr/local/etc/php/conf.d/docker.ini
fi

if [ -n "${PHP_MAX_INPUT_VARS}" ]; then
    echo "max_input_vars = ${PHP_MAX_INPUT_VARS}" >> /usr/local/etc/php/conf.d/docker.ini
fi

PHP_EXPOSE_PHP=${PHP_EXPOSE_PHP:-Off}
if [ -n "${PHP_EXPOSE_PHP}" ]; then
    echo "expose_php = ${PHP_EXPOSE_PHP}" >> /usr/local/etc/php/conf.d/docker.ini
fi

if [ -n "${PHP_MAX_EXECUTION_TIME}" ]; then
    echo "max_execution_time = ${PHP_MAX_EXECUTION_TIME}" >> /usr/local/etc/php/conf.d/docker.ini
fi

if [ -n "${PHP_POST_MAX_SIZE}" ]; then
    echo "post_max_size = ${PHP_POST_MAX_SIZE}" >> /usr/local/etc/php/conf.d/docker.ini
fi

if [ -n "${PHP_UPLOAD_MAX_FILESIZE}" ]; then
    echo "upload_max_filesize = ${PHP_UPLOAD_MAX_FILESIZE}" >> /usr/local/etc/php/conf.d/docker.ini
fi


# Configure OPcache for Maximum Performance
if [ -n "${PHP_OPCACHE_MEMORY_CONSUMPTION}" ]; then
    echo "opcache.memory_consumption = ${PHP_OPCACHE_MEMORY_CONSUMPTION}" >> /usr/local/etc/php/conf.d/docker.ini
fi
if [ -n "${PHP_OPCACHE_MAX_ACCELERATED_FILES}" ]; then
    echo "opcache.max_accelerated_files = ${PHP_OPCACHE_MAX_ACCELERATED_FILES}" >> /usr/local/etc/php/conf.d/docker.ini
fi

# Don't Check PHP Files Timestamps
if [ -n "${PHP_OPCACHE_VALIDATE_TIMESTAMPS}" ]; then
    echo "opcache.validate_timestamps = ${PHP_OPCACHE_VALIDATE_TIMESTAMPS}" >> /usr/local/etc/php/conf.d/docker.ini
fi

# Configure the PHP realpath Cache
if [ -n "${PHP_REALPATH_CACHE_SIZE}" ]; then
    echo "realpath_cache_size = ${PHP_REALPATH_CACHE_SIZE}" >> /usr/local/etc/php/conf.d/docker.ini
fi
if [ -n "${PHP_REALPATH_CACHE_TTL}" ]; then
    echo "realpath_cache_ttl = ${PHP_REALPATH_CACHE_TTL}" >> /usr/local/etc/php/conf.d/docker.ini
fi


# php-fpm config
if [ -n "${PHPFPM_PM_MAX_CHILDREN}" ]; then
    sed -i -e "s|^pm\.max_children = 5|pm.max_children = ${PHPFPM_PM_MAX_CHILDREN}|" /usr/local/etc/php-fpm.d/www.conf
fi

if [ -n "${PHPFPM_PM_START_SERVERS}" ]; then
    sed -i -e "s|^pm\.start_servers = 2|pm.start_servers = ${PHPFPM_PM_START_SERVERS}|" /usr/local/etc/php-fpm.d/www.conf
fi

if [ -n "${PHPFPM_PM_MIN_SPARE_SERVERS}" ]; then
    sed -i -e "s|^pm\.min_spare_servers = 1|pm.min_spare_servers = ${PHPFPM_PM_MIN_SPARE_SERVERS}|" /usr/local/etc/php-fpm.d/www.conf
fi

if [ -n "${PHPFPM_PM_MAX_SPARE_SERVERS}" ]; then
    sed -i -e "s|^pm\.max_spare_servers = 3|pm.max_spare_servers = ${PHPFPM_PM_MAX_SPARE_SERVERS}|" /usr/local/etc/php-fpm.d/www.conf
fi

if [ -n "${PHPFPM_PM_STATUS_PATH}" ]; then
    sed -i -e "s|^;pm.status_path = /status|pm.status_path = ${PHPFPM_PM_STATUS_PATH}|" /usr/local/etc/php-fpm.d/www.conf
fi

if [ -n "${PHPFPM_PING_PATH}" ]; then
    sed -i -e "s|^;ping.path = /ping|ping.path = ${PHPFPM_PING_PATH}|" /usr/local/etc/php-fpm.d/www.conf
fi

if [ -n "${PHPFPM_REQUEST_TERMINATE_TIMEOUT}" ]; then
    sed -i -e "s|^;request_terminate_timeout = 0|request_terminate_timeout = ${PHPFPM_REQUEST_TERMINATE_TIMEOUT}|" /usr/local/etc/php-fpm.d/www.conf
fi


# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- php-fpm "$@"
fi

exec "$@"
